name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: self-hosted
    environment: TEST
    steps:
      - name: Use variables
        run: |
          echo "repository variable : ${{ vars.VAR_TEST1 }}"
          echo "repository secret : ${{ secrets.SECRET_TEST1 }}"
