name: First Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - TEST
          - INT
          - PROD
jobs:
  first-job:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Use variables
        run: |
          echo "selected environment : ${{ github.event.inputs.environment }}"
          echo "repository variable : ${{ vars.VAR_TEST1 }}"
          echo "repository secret : ${{ secrets.SECRET_TEST1 }}"
      - name: If environment == PROD
        if: ${{ github.event.inputs.environment }} == PROD
        run: echo "ENVIRONMENT IS PROD!"
