name: First Workflow
on:
  workflow_dispatch:
#    inputs:
#      environment:
#        type: choice
#        description: Environment
#        options:
#          - TEST
#          - INT
#          - PROD

jobs:
  first-job:
    runs-on: self-hosted
#    env:
#      BUILD_VERSION: 0.0.0

#    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: checkout repo
        uses: actions/checkout@master

      - name: Use variables
        run: |
          BUILD_VERSION=`cat ./VERSION` >> $GITHUB_ENV
          echo "FINAL VALUE: $BUILD_VERSION"
          echo "ENV VALUE : ${{ env.BUILD_VERSION }}"
          echo "${{ github.repository }}"
          echo "${{ github.ref_name }}"

#          echo "INITIAL VALUE: $BUILD_VERSION"
#          echo `cat ./VERSION`

#          echo "selected environment : ${{ github.event.inputs.environment }}"
#          echo "repository variable : ${{ vars.VAR_TEST1 }}"
#          echo "repository secret : ${{ secrets.SECRET_TEST1 }}"
#      - name: If environment == PROD
#        if: github.event.inputs.environment == 'PROD'
#        run: echo "ENVIRONMENT IS PROD!"
