name: First Workflow
on:
  workflow_dispatch:
#    inputs:
#      environment:
#        type: choice
#        description: Environment
#        options:
#          - TEST
#          - INT
#          - PROD
env:
  BUILD_VERSION: 0.0.0

jobs:
  first-job:
    runs-on: self-hosted

#    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: checkout repo
        uses: actions/checkout@master

      - name: Use variables
        id: set_build_version
        run: |
          echo "INITIAL VALUE: $BUILD_VERSION"
          BUILD_VERSION=`cat ./VERSION` >> $GITHUB_ENV
          echo "FINAL VALUE: $BUILD_VERSION"
          echo "ENV VALUE : ${{ env.BUILD_VERSION }}"
          echo "::set-output name=build_version::$BUILD_VERSION"
          echo "OUTPUTS: ${{ steps.set_build_version.outputs.build_version }}"
          echo "${{ github.ref_name }}"
          echo "${{ github.run_number }}"

#          echo "selected environment : ${{ github.event.inputs.environment }}"
#          echo "repository variable : ${{ vars.VAR_TEST1 }}"
#          echo "repository secret : ${{ secrets.SECRET_TEST1 }}"
#      - name: If environment == PROD
#        if: github.event.inputs.environment == 'PROD'
#        run: echo "ENVIRONMENT IS PROD!"
